<?php

namespace TripBundle\Repository;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class TripRepository extends EntityRepository
{
    public function findOneByTripName($tripName)
    {
        return $this->findOneBy(array(
            'tripName' => $tripName
        ));
    }
}
