<?php

namespace TripBundle\Repository;

/**
 * TripTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
