<?php

namespace BusRouteBundle\Repository;

/**
 * BusRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusRouteRepository extends \Doctrine\ORM\EntityRepository
{
}
