<?php

namespace BusRouteBundle\Repository;

/**
 * BusRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class BusRouteRepository extends EntityRepository
{
    public function findOneByRouteName($routeName)
    {
        return $this->findOneBy(array(
            'routeName' => $routeName
        ));
    }
}
