<?php

namespace BusBundle\Repository;

/**
 * BusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusRepository extends \Doctrine\ORM\EntityRepository
{
}
