<?php

namespace BusBundle\Repository;


/**
 * BusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class BusRepository extends EntityRepository
{
    public function findOneByBusRegistration($busRegistration)
    {
        return $this->findOneBy(array(
            'busRegistration' => $busRegistration
        ));
    }
}
