<?php

namespace BusBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * BusTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusTypeRepository extends EntityRepository
{
    public function findRecordByBusType($busType) 
    {
        return $this->findOneBy([
            'type' => $busType
        ]);
    }
}
