<?php

namespace BusBundle\Repository;

/**
 * BusTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
