<?php

namespace ApiLogsBundle\Repository;

/**
 * BusRouteTableLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusRouteTableLogRepository extends \Doctrine\ORM\EntityRepository
{
}
