<?php

namespace ApiLogsBundle\Repository;

/**
 * BusTableLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusTableLogRepository extends \Doctrine\ORM\EntityRepository
{
}
