<?php

namespace ApiLogsBundle\Repository;

/**
 * BusTypeTableLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusTypeTableLogRepository extends \Doctrine\ORM\EntityRepository
{
}
