<?php

namespace ApiLogsBundle\Repository;

/**
 * TripTableLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripTableLogRepository extends \Doctrine\ORM\EntityRepository
{
}
