<?php

namespace ApiLogsBundle\Repository;

/**
 * UserTableLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTableLogRepository extends \Doctrine\ORM\EntityRepository
{
}
